### ISSUE TITLE
BD Tabla Token 

### ISSUE THREAD

**Issue by Pandiurex** [Pandiurex/Foraneos-UDG-Api#81]
* Tabla para manejar todas nuestros Token.
* Crear una tabla en la base de datos con los siguientes valores:

|Token|Valor|Descripción
--------|--------------|-----------
|id|int|primary key
|token| varchar(255)|unique
|created_at|datetime|not null
|expires|datetime|not null
|type|varchar(50)|not null
|status|boolean|not null
|user_id|int|foreing key

* Nota: El tipo de datos son una propuesta.

**Comment by Mgmez** [comment]
Table created
